
jenkins:
  systemMessage: "Jenkins CI Demo (auto-configured via JCasC)"
  numExecutors: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin123"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true
unclassified:
  location:
    url: "http://localhost:8080/"
jobs:
  - script: >
      pipelineJob('Demo-CI-Pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote { url('file:///demo-repo') }
                branch('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        triggers { scm('* * * * *') }
      }
